rem pablo.almaguer@logicinfo.com


rem ::Windows Classpath::
C:\ATG\ATG11.2\Agent\ExternalUsers\lib\classes.jar
C:\ATG\ATG11.2\Agent\lib\classes.jar
C:\ATG\ATG11.2\AssetUI\lib\classes.jar
C:\ATG\ATG11.2\BCC\lib\classes.jar
C:\ATG\ATG11.2\BCC\lib\commons-fileupload-1.3.1.jar
C:\ATG\ATG11.2\BCC\lib\commons-io-2.4.jar
C:\ATG\ATG11.2\BCC\lib\commons-lang-2.5.jar
C:\ATG\ATG11.2\BCC\Versioned\lib\classes.jar
C:\ATG\ATG11.2\BIZUI\lib\classes.jar
C:\ATG\ATG11.2\CAF11.2\CAF\lib\classes.jar
C:\ATG\ATG11.2\CAF11.2\CAF\lib\jfreechart\jcommon-0.9.3.jar
C:\ATG\ATG11.2\CAF11.2\CAF\lib\jfreechart\jfreechart-0.9.18.jar
C:\ATG\ATG11.2\CAF11.2\CAF\lib\jfreechart\log4j-1.2.17.jar
C:\ATG\ATG11.2\ContentMgmt\lib\classes.jar
C:\ATG\ATG11.2\CSC-UI11.2\DCS-CSR-UI\lib\classes.jar
C:\ATG\ATG11.2\CSC11.2\DCS-CSR\lib\classes.jar
C:\ATG\ATG11.2\CSC11.2\DCS-CSR\Management\lib\classes.jar
C:\ATG\ATG11.2\DAF\Endeca\Assembler\lib\classes.jar
C:\ATG\ATG11.2\DAF\Endeca\Assembler\lib\endeca_assembler_core-11.2.0.jar
C:\ATG\ATG11.2\DAF\Endeca\Assembler\lib\endeca_assembler_navigation-11.2.0.jar
C:\ATG\ATG11.2\DAF\Endeca\Assembler\lib\endeca_navigation-6.5.2.jar
C:\ATG\ATG11.2\DAF\Endeca\Base\lib\classes.jar
C:\ATG\ATG11.2\DAF\Endeca\Index\lib\classes.jar
C:\ATG\ATG11.2\DAF\Search\Base\lib\classes.jar
C:\ATG\ATG11.2\DAF\Search\Base\lib\rmi-stub-classes.jar
C:\ATG\ATG11.2\DAF\Search\common\lib\classes.jar
C:\ATG\ATG11.2\DAF\Search\Index\lib\classes.jar
C:\ATG\ATG11.2\DAF\TextSearch\Base\lib\classes.jar
C:\ATG\ATG11.2\DAF\TextSearch\Index\lib\classes.jar
C:\ATG\ATG11.2\DAF\TextSearch\LiveIndex\lib\classes.jar
C:\ATG\ATG11.2\DafEar\base\lib\classes.jar
C:\ATG\ATG11.2\DafEar\JBoss\lib\classes.jar
C:\ATG\ATG11.2\DafEar\Tomcat\lib\classes.jar
C:\ATG\ATG11.2\DafEar\WebLogic\lib\classes.jar
C:\ATG\ATG11.2\DafEar\WebSphere\lib\classes.jar
C:\ATG\ATG11.2\DAS-UI\lib\jhall.jar
C:\ATG\ATG11.2\DAS-UI\lib\uiclasses.jar
C:\ATG\ATG11.2\DAS-UI\lib\uiresources.jar
C:\ATG\ATG11.2\DAS\lib\cglib-nodep-2.1_3.jar
C:\ATG\ATG11.2\DAS\lib\classes.jar
C:\ATG\ATG11.2\DAS\lib\ice.jar
C:\ATG\ATG11.2\DAS\lib\jline-0.9.94.jar
C:\ATG\ATG11.2\DAS\lib\jsp-api.jar
C:\ATG\ATG11.2\DAS\lib\resources.jar
C:\ATG\ATG11.2\DAS\lib\servlet.jar
C:\ATG\ATG11.2\DAS\lib\spring-aop-1.2-rc1.jar
C:\ATG\ATG11.2\DAS\lib\validation-api-1.0.0.GA.jar
C:\ATG\ATG11.2\DCS\lib\classes.jar
C:\ATG\ATG11.2\DCS\lib\resources.jar
C:\ATG\ATG11.2\DPS-UI\AccessControl\lib\classes.jar
C:\ATG\ATG11.2\DPS-UI\lib\classes.jar
C:\ATG\ATG11.2\DPS\lib\classes.jar
C:\ATG\ATG11.2\DPS\lib\resources.jar
C:\ATG\ATG11.2\DSS\lib\classes.jar
C:\ATG\ATG11.2\DSS\lib\resources.jar
C:\ATG\ATG11.2\FlexUI\lib\backport-util-concurrent-2.2.jar
C:\ATG\ATG11.2\FlexUI\lib\cfgatewayadapter-3.2.0.3978.jar
C:\ATG\ATG11.2\FlexUI\lib\classes.jar
C:\ATG\ATG11.2\FlexUI\lib\commons-codec-1.3.jar
C:\ATG\ATG11.2\FlexUI\lib\concurrent-1.3.3.jar
C:\ATG\ATG11.2\FlexUI\lib\flex-messaging-3.2.0.3978.jar
C:\ATG\ATG11.2\FlexUI\lib\httpclient-4.2.5.jar
C:\ATG\ATG11.2\FlexUI\lib\httpcore-4.2.4.jar
C:\ATG\ATG11.2\GN\Core\lib\classes.jar
C:\ATG\ATG11.2\GN\Core\lib\commons-collections-3.2.1.jar
C:\ATG\ATG11.2\GN\Core\lib\commons-lang3-3.1.jar
C:\ATG\ATG11.2\GN\Core\lib\commons-vfs2-2.0.jar
C:\ATG\ATG11.2\GN\Core\lib\jsch-0.1.54.jar
C:\ATG\ATG11.2\GN\Core\lib\migrationframework.jar
C:\ATG\ATG11.2\GN\Core\lib\opencsv-2.2.jar
C:\ATG\ATG11.2\GN\Core\lib\resources.jar
C:\ATG\ATG11.2\GN\DataMigration\lib\classes.jar
C:\ATG\ATG11.2\GN\Endeca\lib\classes.jar
C:\ATG\ATG11.2\GN\Endeca\lib\resources.jar
C:\ATG\ATG11.2\GN\Integration\ORCE\lib\cardservices.jar
C:\ATG\ATG11.2\GN\Integration\ORCE\lib\classes.jar
C:\ATG\ATG11.2\GN\Integration\ORCE\lib\commons-lang3-3.1.jar
C:\ATG\ATG11.2\GN\Integration\ORCE\lib\customerservices.jar
C:\ATG\ATG11.2\GN\Integration\ORCE\lib\transactionservices.jar
C:\ATG\ATG11.2\GN\Integration\OROB\lib\classes.jar
C:\ATG\ATG11.2\GN\Integration\OROB\lib\commons-lang3-3.1.jar
C:\ATG\ATG11.2\GN\Integration\OROB\lib\locateservices.jar
C:\ATG\ATG11.2\GN\POCFulfillment\lib\classes.jar
C:\ATG\ATG11.2\GN\Service\lib\classes.jar
C:\ATG\ATG11.2\GN\Store\lib\barcode4j.jar
C:\ATG\ATG11.2\GN\Store\lib\cardservices.jar
C:\ATG\ATG11.2\GN\Store\lib\classes.jar
C:\ATG\ATG11.2\GN\Store\lib\commons-validator-1.5.1.jar
C:\ATG\ATG11.2\GN\Store\lib\gson-2.6.2.jar
C:\ATG\ATG11.2\GN\StoreModule\Core\lib\classes.jar
C:\ATG\ATG11.2\GN\StoreModule\Store\lib\classes.jar
C:\ATG\ATG11.2\Publishing\base\lib\classes.jar
C:\ATG\ATG11.2\PublishingAgent\base\lib\agent.jar
C:\ATG\ATG11.2\PublishingAgent\base\lib\classes.jar
C:\ATG\ATG11.2\PubPortlet\lib\classes.jar
C:\ATG\ATG11.2\REST\lib\atg-rest-1.0.jar
C:\ATG\ATG11.2\REST\lib\commons-fileupload-1.3.1.jar
C:\ATG\ATG11.2\REST\lib\commons-io-2.4.jar
C:\ATG\ATG11.2\REST\lib\dom4j-1.6.1.jar
C:\ATG\ATG11.2\REST\lib\org.json.jar
C:\ATG\ATG11.2\RL\lib\RLClient.jar
C:\ATG\ATG11.2\Service-UI11.2\Service-UI\Framework\Agent\lib\classes.jar
C:\ATG\ATG11.2\Service11.2\Service\Framework\Agent\lib\classes.jar
C:\ATG\ATG11.2\Service11.2\Service\Framework\lib\classes.jar
C:\ATG\ATG11.2\Service11.2\Service\Framework\lib\ssce.jar
C:\ATG\ATG11.2\Service11.2\Service\Framework\UI\lib\classes.jar
C:\ATG\ATG11.2\Service11.2\Service\Response\lib\classes.jar
C:\ATG\ATG11.2\Service11.2\Service\Ticketing\lib\classes.jar
C:\ATG\ATG11.2\Ticketing\lib\ticketing.jar
C:\ATG\ATG11.2\WebUI\lib\classes.jar
C:\ATG\ATG11.2\WebUI\Preview\lib\classes.jar
C:\ATG\ATG11.2\WebUI\Preview\Versioned\lib\classes.jar
C:\oracle\10.3.6-Forms11.1.2.1.0\WLS\wlserver_10.3\server\lib\weblogic.jar
C:\oracle\eclipse-jee-mars\configuration\org.eclipse.osgi\79\0\.cp\lib\antdebug.jar
C:\oracle\eclipse-jee-mars\configuration\org.eclipse.osgi\79\0\.cp\lib\remote.jar
C:\oracle\eclipse-jee-mars\configuration\org.eclipse.osgi\80\0\.cp\lib\remoteAnt.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-antlr.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-bcel.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-bsf.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-log4j.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-oro.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-regexp.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-resolver.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-apache-xalan2.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-commons-logging.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-commons-net.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-jai.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-javamail.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-jdepend.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-jmf.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-jsch.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-junit.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-junit4.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-launcher.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-netrexx.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-swing.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant-testutil.jar
C:\oracle\eclipse-jee-mars\plugins\org.apache.ant_1.9.6.v201510161327\lib\ant.jar
C:\oracle\eclipse-jee-mars\plugins\org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar
C:\oracle\java\jdk1.7.0_80\lib\tools.jar

rem ::Variable substitution::
%ATG_HOME%\Agent\ExternalUsers\lib\classes.jar
%ATG_HOME%\Agent\lib\classes.jar
%ATG_HOME%\AssetUI\lib\classes.jar
%ATG_HOME%\BCC\lib\classes.jar
%ATG_HOME%\BCC\lib\commons-fileupload-1.3.1.jar
%ATG_HOME%\BCC\lib\commons-io-2.4.jar
%ATG_HOME%\BCC\lib\commons-lang-2.5.jar
%ATG_HOME%\BCC\Versioned\lib\classes.jar
%ATG_HOME%\BIZUI\lib\classes.jar
%ATG_HOME%\CAF11.2\CAF\lib\classes.jar
%ATG_HOME%\CAF11.2\CAF\lib\jfreechart\jcommon-0.9.3.jar
%ATG_HOME%\CAF11.2\CAF\lib\jfreechart\jfreechart-0.9.18.jar
%ATG_HOME%\CAF11.2\CAF\lib\jfreechart\log4j-1.2.17.jar
%ATG_HOME%\ContentMgmt\lib\classes.jar
%ATG_HOME%\CSC-UI11.2\DCS-CSR-UI\lib\classes.jar
%ATG_HOME%\CSC11.2\DCS-CSR\lib\classes.jar
%ATG_HOME%\CSC11.2\DCS-CSR\Management\lib\classes.jar
%ATG_HOME%\DAF\Endeca\Assembler\lib\classes.jar
%ATG_HOME%\DAF\Endeca\Assembler\lib\endeca_assembler_core-11.2.0.jar
%ATG_HOME%\DAF\Endeca\Assembler\lib\endeca_assembler_navigation-11.2.0.jar
%ATG_HOME%\DAF\Endeca\Assembler\lib\endeca_navigation-6.5.2.jar
%ATG_HOME%\DAF\Endeca\Base\lib\classes.jar
%ATG_HOME%\DAF\Endeca\Index\lib\classes.jar
%ATG_HOME%\DAF\Search\Base\lib\classes.jar
%ATG_HOME%\DAF\Search\Base\lib\rmi-stub-classes.jar
%ATG_HOME%\DAF\Search\common\lib\classes.jar
%ATG_HOME%\DAF\Search\Index\lib\classes.jar
%ATG_HOME%\DAF\TextSearch\Base\lib\classes.jar
%ATG_HOME%\DAF\TextSearch\Index\lib\classes.jar
%ATG_HOME%\DAF\TextSearch\LiveIndex\lib\classes.jar
%ATG_HOME%\DafEar\base\lib\classes.jar
%ATG_HOME%\DafEar\JBoss\lib\classes.jar
%ATG_HOME%\DafEar\Tomcat\lib\classes.jar
%ATG_HOME%\DafEar\WebLogic\lib\classes.jar
%ATG_HOME%\DafEar\WebSphere\lib\classes.jar
%ATG_HOME%\DAS-UI\lib\jhall.jar
%ATG_HOME%\DAS-UI\lib\uiclasses.jar
%ATG_HOME%\DAS-UI\lib\uiresources.jar
%ATG_HOME%\DAS\lib\cglib-nodep-2.1_3.jar
%ATG_HOME%\DAS\lib\classes.jar
%ATG_HOME%\DAS\lib\ice.jar
%ATG_HOME%\DAS\lib\jline-0.9.94.jar
%ATG_HOME%\DAS\lib\jsp-api.jar
%ATG_HOME%\DAS\lib\resources.jar
%ATG_HOME%\DAS\lib\servlet.jar
%ATG_HOME%\DAS\lib\spring-aop-1.2-rc1.jar
%ATG_HOME%\DAS\lib\validation-api-1.0.0.GA.jar
%ATG_HOME%\DCS\lib\classes.jar
%ATG_HOME%\DCS\lib\resources.jar
%ATG_HOME%\DPS-UI\AccessControl\lib\classes.jar
%ATG_HOME%\DPS-UI\lib\classes.jar
%ATG_HOME%\DPS\lib\classes.jar
%ATG_HOME%\DPS\lib\resources.jar
%ATG_HOME%\DSS\lib\classes.jar
%ATG_HOME%\DSS\lib\resources.jar
%ATG_HOME%\FlexUI\lib\backport-util-concurrent-2.2.jar
%ATG_HOME%\FlexUI\lib\cfgatewayadapter-3.2.0.3978.jar
%ATG_HOME%\FlexUI\lib\classes.jar
%ATG_HOME%\FlexUI\lib\commons-codec-1.3.jar
%ATG_HOME%\FlexUI\lib\concurrent-1.3.3.jar
%ATG_HOME%\FlexUI\lib\flex-messaging-3.2.0.3978.jar
%ATG_HOME%\FlexUI\lib\httpclient-4.2.5.jar
%ATG_HOME%\FlexUI\lib\httpcore-4.2.4.jar
%ATG_HOME%\GN\Core\lib\classes.jar
%ATG_HOME%\GN\Core\lib\commons-collections-3.2.1.jar
%ATG_HOME%\GN\Core\lib\commons-lang3-3.1.jar
%ATG_HOME%\GN\Core\lib\commons-vfs2-2.0.jar
%ATG_HOME%\GN\Core\lib\jsch-0.1.54.jar
%ATG_HOME%\GN\Core\lib\migrationframework.jar
%ATG_HOME%\GN\Core\lib\opencsv-2.2.jar
%ATG_HOME%\GN\Core\lib\resources.jar
%ATG_HOME%\GN\DataMigration\lib\classes.jar
%ATG_HOME%\GN\Endeca\lib\classes.jar
%ATG_HOME%\GN\Endeca\lib\resources.jar
%ATG_HOME%\GN\Integration\ORCE\lib\cardservices.jar
%ATG_HOME%\GN\Integration\ORCE\lib\classes.jar
%ATG_HOME%\GN\Integration\ORCE\lib\commons-lang3-3.1.jar
%ATG_HOME%\GN\Integration\ORCE\lib\customerservices.jar
%ATG_HOME%\GN\Integration\ORCE\lib\transactionservices.jar
%ATG_HOME%\GN\Integration\OROB\lib\classes.jar
%ATG_HOME%\GN\Integration\OROB\lib\commons-lang3-3.1.jar
%ATG_HOME%\GN\Integration\OROB\lib\locateservices.jar
%ATG_HOME%\GN\POCFulfillment\lib\classes.jar
%ATG_HOME%\GN\Service\lib\classes.jar
%ATG_HOME%\GN\Store\lib\barcode4j.jar
%ATG_HOME%\GN\Store\lib\cardservices.jar
%ATG_HOME%\GN\Store\lib\classes.jar
%ATG_HOME%\GN\Store\lib\commons-validator-1.5.1.jar
%ATG_HOME%\GN\Store\lib\gson-2.6.2.jar
%ATG_HOME%\GN\StoreModule\Core\lib\classes.jar
%ATG_HOME%\GN\StoreModule\Store\lib\classes.jar
%ATG_HOME%\Publishing\base\lib\classes.jar
%ATG_HOME%\PublishingAgent\base\lib\agent.jar
%ATG_HOME%\PublishingAgent\base\lib\classes.jar
%ATG_HOME%\PubPortlet\lib\classes.jar
%ATG_HOME%\REST\lib\atg-rest-1.0.jar
%ATG_HOME%\REST\lib\commons-fileupload-1.3.1.jar
%ATG_HOME%\REST\lib\commons-io-2.4.jar
%ATG_HOME%\REST\lib\dom4j-1.6.1.jar
%ATG_HOME%\REST\lib\org.json.jar
%ATG_HOME%\RL\lib\RLClient.jar
%ATG_HOME%\Service-UI11.2\Service-UI\Framework\Agent\lib\classes.jar
%ATG_HOME%\Service11.2\Service\Framework\Agent\lib\classes.jar
%ATG_HOME%\Service11.2\Service\Framework\lib\classes.jar
%ATG_HOME%\Service11.2\Service\Framework\lib\ssce.jar
%ATG_HOME%\Service11.2\Service\Framework\UI\lib\classes.jar
%ATG_HOME%\Service11.2\Service\Response\lib\classes.jar
%ATG_HOME%\Service11.2\Service\Ticketing\lib\classes.jar
%ATG_HOME%\Ticketing\lib\ticketing.jar
%ATG_HOME%\WebUI\lib\classes.jar
%ATG_HOME%\WebUI\Preview\lib\classes.jar
%ATG_HOME%\WebUI\Preview\Versioned\lib\classes.jar
%ANT_HOME%\lib\ant-antlr.jar
%ANT_HOME%\lib\ant-apache-bcel.jar
%ANT_HOME%\lib\ant-apache-bsf.jar
%ANT_HOME%\lib\ant-apache-log4j.jar
%ANT_HOME%\lib\ant-apache-oro.jar
%ANT_HOME%\lib\ant-apache-regexp.jar
%ANT_HOME%\lib\ant-apache-resolver.jar
%ANT_HOME%\lib\ant-apache-xalan2.jar
%ANT_HOME%\lib\ant-commons-logging.jar
%ANT_HOME%\lib\ant-commons-net.jar
%ANT_HOME%\lib\ant-jai.jar
%ANT_HOME%\lib\ant-javamail.jar
%ANT_HOME%\lib\ant-jdepend.jar
%ANT_HOME%\lib\ant-jmf.jar
%ANT_HOME%\lib\ant-jsch.jar
%ANT_HOME%\lib\ant-junit.jar
%ANT_HOME%\lib\ant-junit4.jar
%ANT_HOME%\lib\ant-launcher.jar
%ANT_HOME%\lib\ant-netrexx.jar
%ANT_HOME%\lib\ant-swing.jar
%ANT_HOME%\lib\ant-testutil.jar
%ANT_HOME%\lib\ant.jar
%ECLIPSE_HOME%\configuration\org.eclipse.osgi\79\0\.cp\lib\antdebug.jar
%ECLIPSE_HOME%\configuration\org.eclipse.osgi\79\0\.cp\lib\remote.jar
%ECLIPSE_HOME%\configuration\org.eclipse.osgi\80\0\.cp\lib\remoteAnt.jar
%ECLIPSE_HOME%\plugins\org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar
%JAVA_HOME%\lib\tools.jar
%WLS_HOME%\server\lib\weblogic.jar